<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class CMSDomainsProfileHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="int") */
        if (isset($data['Pin']) || (! empty($this->class->fieldMappings['Pin']['nullable']) && array_key_exists('Pin', $data))) {
            $value = $data['Pin'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['Pin']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['Pin']->setValue($document, $return);
            $hydratedData['Pin'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['FirstName']) || (! empty($this->class->fieldMappings['FirstName']['nullable']) && array_key_exists('FirstName', $data))) {
            $value = $data['FirstName'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['FirstName']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['FirstName']->setValue($document, $return);
            $hydratedData['FirstName'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['LastName']) || (! empty($this->class->fieldMappings['LastName']['nullable']) && array_key_exists('LastName', $data))) {
            $value = $data['LastName'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['LastName']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['LastName']->setValue($document, $return);
            $hydratedData['LastName'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['Birthday'])) {
            $value = $data['Birthday'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['Birthday']->setValue($document, clone $return);
            $hydratedData['Birthday'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['Gender']) || (! empty($this->class->fieldMappings['Gender']['nullable']) && array_key_exists('Gender', $data))) {
            $value = $data['Gender'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['Gender']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['Gender']->setValue($document, $return);
            $hydratedData['Gender'] = $return;
        }

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['Id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['Id']['type'];
                $return = $value instanceof \MongoId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['Id']->setValue($document, $return);
            $hydratedData['Id'] = $return;
        }
        return $hydratedData;
    }
}